cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  css_framework: bootstrap
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: 2025.2.2
  author_name: The ABBA Initiative
  ci: github_actions
  css_framework: bootstrap
  css_theme: bootstrap-material
  database: postgres
  deploy_platform: kamal
  description: The most amazing SaaS application the world has ever seen
  docker_setup: default
  domain_name: localhost:8000
  email: aldesabido@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: ysystech
  include_static_files: y
  marketing_email_platform: none
  plugin_chat_mode: llm
  plugins:
  - chat
  post_process: y
  project_name: CDT Accounting
  project_slug: cdt_accounting
  python_package_manager: pip-tools
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_api_auth: n
  use_api_keys: y
  use_async: n
  use_celery: n
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: n
  use_docker: y
  use_ecommerce_example: n
  use_examples: n
  use_flowbite: n
  use_health_checks: n
  use_impersonation: n
  use_sentry: n
  use_shadcn: n
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: n
  use_wagtail: n
